
name: Purple Cow Properties
description: Don't follow the herd
avatar: http://purplecowproperties.co.uk/images/logo-default.png

contact:
  phone: 0161 839 0735
  email: info@purplecowproperties.co.uk

social:
  twitter: purplecowproper
  facebook: purplecowproperties
  linkedin: purple-cow-properties

url: http://purplecowproperties.co.uk/

baseurl: ""

collections:
  testimonials:
    output: true

markdown: kramdown

sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed
  
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem