
name: Purple Cow Properties
description: Don't follow the herd
avatar: https://purplecowproperties.co.uk/images/logo-default.png

contact:
  phone: 91a1a0a7a0b1a9a2a8b1a1a6a2a4
  email: d5b4bdbaac95a5a0a7a5b9b0b6baa2a5a7baa5b0a7a1bcb0a6fbb6bafba0be

social:
  twitter: purplecowproper
  facebook: purplecowproperties
  linkedin: purple-cow-properties

url: https://purplecowproperties.co.uk/

baseurl: ""

collections:
  testimonials:
    output: true

markdown: kramdown

sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed
  
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-redirect-from
